tasks:
  - name: Install Miniconda
    init: |
      curl https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh -o ~/miniconda.sh
      bash ~/miniconda.sh -b -p miniconda
      miniconda/bin/pip install -r requirements.txt
    command: |
      miniconda/bin/conda init > /dev/null
      exec bash
    
github:
  prebuilds:
    branches: true

ports:
  - name: Streamlit Dashboard
    description: The Default Streamlit Server Port
    port: 8501
    visibility: public
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
    - mechatroner.rainbow-csv
    - akosyakov.gitpod-monitor